image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
- cmd: >-
    mkdir build &&
    cd build &&
    cmake c:\projects\source -T llvm -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_LIBDL=OFF -DKokkos_ENABLE_PROFILING=OFF &&
    cmake --build . --target install &&
    ctest -C Debug -V
