NVIDIA-GH200:
  stage: test
  tags: [nvidia-gh200]
  image: masterleinad/kokkos-nvcc:12.6.1
  script:
    - cmake -B build -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_HOPPER90=ON -DKokkos_ENABLE_IMPL_CUDA_UNIFIED_MEMORY=ON -DKokkos_ENABLE_TESTS=ON
    - cmake --build build -j48
    - cd build
    - ctest -V

INTEL-DATA-CENTER-MAX-1100:
  stage: test
  tags: [intel-data-center-max-1100]
  image: intel/oneapi-basekit:2024.2.1-0-devel-ubuntu22.04
  script:
    - cmake -B build -DCMAKE_CXX_COMPILER=icpx -DKokkos_ENABLE_SYCL=ON -DKokkos_ARCH_INTEL_PVC=ON -DKokkos_ENABLE_TESTS=ON
    - cmake --build build -j48
    - cd build
    - ctest -V
