name: github-windows

on:
  workflow_call:
  push:

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}-win-x64
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

permissions: read-all

jobs:
  windows-serial:
    # Serial build on Windows
    name: Serial VS-2022
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: configure
      shell: bash
      run: |
        cmake -B build -DKokkos_ENABLE_EXPERIMENTAL_CXX20_MODULES=ON -DCMAKE_CXX_STANDARD=20 -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_TESTS=ON
    - name: build library
      shell: bash
      run: |
        cmake --build build --parallel 4 --config Release
    - name: run tests
      shell: bash
      run: |
        export PATH="$(pwd)/build/core/src/Release:$(pwd)/build/containers/src/Release:$PATH"
        ctest --test-dir build -C Release -j 4 --output-on-failure
