name: github-Windows
on: [push, pull_request]

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  CI:
    continue-on-error: true
    strategy:
      matrix:
        os: ['windows-2019', 'windows-2022']
        enable_cuda: ['OFF', 'ON']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Maybe install CUDA
        if: ${{ matrix.enable_cuda == 'ON' }}
        run: |
          cinst cuda --version 11.7.0.51601
          echo "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7" >> $env:GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v2.2.0
      - name: Configure Kokkos
        run: |
          refreshenv
          echo "PATH: $env:PATH"
          echo "CUDA_PATH: $env:CUDA_PATH"
          cmake . -B builddir `
            -DKokkos_ENABLE_CUDA=${{ matrix.enable_cuda }} `
            -DKokkos_ENABLE_CUDA_LAMBDA=${{ matrix.enable_cuda }} `
            -DKokkos_ARCH_VOLTA70=${{ matrix.enable_cuda }} `
            -DKokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE=${{ matrix.enable_cuda }} `
            -DKokkos_ENABLE_TESTS=ON `
            -DKokkos_ENABLE_EXAMPLES=ON `
            -DKokkos_ENABLE_DEPRECATED_CODE_3=ON `
            -DKokkos_ENABLE_DEPRECATION_WARNINGS=OFF `
            -DCMAKE_CXX_FLAGS="/W0 /EHsc" `
            -DCMAKE_BUILD_TYPE=Debug; `
            get-content D:/a/kokkos/kokkos/builddir/CMakeFiles/CMakeOutput.log;`
            get-content D:/a/kokkos/kokkos/builddir/CMakeFiles/CMakeError.log
      - name: Build
        run: |
          cmake --build builddir --parallel 2
      - name: Maybe run tests
        if: ${{ matrix.enable_cuda == 'OFF' }}
        working-directory: builddir
        run:  ctest -C Debug --output-on-failure
