name: github-windows

on:
  workflow_call:
  push:

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}-win-x64
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

permissions: read-all

jobs:
  windows-clang:
   # Threads build on Windows using ClangCL
    name: Threads Clang VS-2022
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: configure
      shell: bash
      run: |
        cmake -B build -T ClangCL -DKokkos_ENABLE_SERIAL=ON -DKokkos_ENABLE_THREADS=ON -DKokkos_ENABLE_TESTS=ON
    - name: build library
      shell: bash
      run: |
        cmake --build build --parallel 4 --config Release
    - name: run tests
      shell: bash
      run: |
        ctest --test-dir build -C Release -j 4 -V
