name: github-CI

on: [push, pull_request]

jobs:
  windows-clang:
    # Serial build on Windows
    name: Windows Serial
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: info
      run: |
        cmake --version
        wmic logicaldisk get size, freespace, caption
    - name: configure
      shell: bash
      run: |
        mkdir build
        mkdir c:/project
        cd build
        cmake -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_LIBDL=OFF -DKokkos_ENABLE_PROFILING=OFF -T llvm ..
    - name: build library
      shell: bash
      run: |
        cmake --build build  --target install -- -m
        cd c:/project
        7z a kokkos-windows.zip *
    - name: test library
      shell: bash
      run: |
        cmake --build build  --target test -- -m
