name: github-windows

on:
  push:
  pull_request:

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

permissions: read-all

jobs:
  windows-cuda:
    # Cuda build on Windows
    name: Windows Cuda
    runs-on: windows-2022

    steps:
    - name: install cuda
      shell: bash
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/12.5.0/network_installers/cuda_12.5.0_windows_network.exe
        cuda_12.5.0_windows_network.exe -sn nvcc_12.5
    - uses: actions/checkout@v4
    - name: configure
      shell: bash
      run: |
        mkdir build
        mkdir c:/project
        cd build
        cmake -DKokkos_ENABLE_CUDA=ON -DKokkos_ARCH_VOLTA70=ON -DKokkos_ENABLE_TESTS=ON -DKokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE=ON ..
    - name: build library
      shell: bash
      run: |
        cmake --build build --parallel 2 --config Release
