name: github-windows

on: [push, pull_request]

jobs:
  windows:
    name: Windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2016]

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -DKokkos_ENABLE_TESTS=ON -DCMAKE_CXX_FLAGS="/W0 /EHsc" -DKokkos_ENABLE_DEPRECATED_CODE_3=ON ..
    - name: build library
      run: |
        cmake --build build  --target install -- -m
    - name: test library
      run: |
        cmake --build build  --target test -- -m
